<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>FxKit</Title>
  </PropertyGroup>
  <PropertyGroup>
    <EnablePackageValidation>true</EnablePackageValidation>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FxKit.CompilerServices.Annotations\FxKit.CompilerServices.Annotations.csproj" />
    <ProjectReference Include="..\FxKit.CompilerServices\FxKit.CompilerServices.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
  </ItemGroup>
</Project>