namespace FxKit.CompilerServices.Utilities;

internal static class SourceGenerationHelper
{
    /// <summary>
    ///     Header to insert for autogenerated files.
    /// </summary>
    public const string AutoGeneratedHeader =
        """
        /// <autogenerated>
        ///    This code was generated by FxKit. Manual edits will not be saved.
        /// </autogenerated>
        """;

    /// <summary>
    ///     Header to insert for autogenerated files.
    /// </summary>
    public const string NullableEnabledDirective = "#nullable enable";
}
