<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>FxKit Testing</Title>
    <Description>Test utilities for asserting on FxKit data types.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FxKit\FxKit.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>
</Project>