<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>FxKit Testing</Title>
    <Description>Test utilities for asserting on FxKit data types.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FxKit\FxKit.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Update="MinVer" />
  </ItemGroup>
</Project>